cookie:
  expiry_days: 7
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    adam@projectfuelnow.com:
      email: adam@projectfuelnow.com
      name: Adam G
      password: 
    angel@projectfuelnow.com:
      email: angel@projectfuelnow.com
      name: Angel Paruas
      password: 
    howard@projectfuelnow.com:
      email: howard@projectfuelnow.com
      name: Howard B
      password: 
preauthorized:
  emails:
  - angel@projectfuelnowx.com
